### ISSUE TITLE
TD assert failed: Hmm his got changed somewhere???

### ISSUE THREAD

**Issue by 0x506978656c** [0x506978656c/Single-BDScord#2]
Recent issues after this commit [ddce48f](https://github.com/bdsx/bdsx/commit/ddce48f44db1500e7470b5fdbdf732b5280e4ed5l) first highlighted by [iceraven775](https://github.com/iceraven775) in https://github.com/bdsx/bdsx/issues/287

Due to library `sneakfetch` in `webhook-discord` throwing a SSL issue from Chakra-core. Similar seen on Linux

Windows: - Caches
![image](https://user-images.githubusercontent.com/66031115/152676986-d73fb56f-603f-461c-9c04-1ab926d9463c.png)

Linux: - Evil 
```
(node:8) UnhandledPromiseRejectionWarning: Error: Error generating ticket keys
   at SecureContext (_tls_common.js:66:3)
   at createSecureContext (_tls_common.js:93:3)
   at connect (_tls_wrap.js:1226:3)
   at createConnection (https.js:119:3)
   at createSocket (_http_agent.js:227:3)
   at addRequest (_http_agent.js:185:5)
   at ClientRequest (_http_client.js:261:5)
   at request (https.js:300:3)
   at buildRequest (Z:\opt\bdsx\node_modules\snekfetch\src\node\index.js:48:3)
   at Snekfetch (Z:\opt\bdsx\node_modules\snekfetch\src\index.js:36:5)
   at runMethod (Z:\opt\bdsx\node_modules\snekfetch\src\index.js:247:5)
   at Webhook (Z:\opt\bdsx\node_modules\webhook-discord\lib\webhook.js:19:9)
   at Anonymous function (Z:\opt\bdsx\plugins\single-BDScord\mod\BDScord.ts:26:14)
```

Possible fixes can include a timeout apparently but this needs to be tested. The issue originates from https://github.com/chakra-core/ChakraCore/blob/master/lib/Runtime/Debug/TTEventLog.h#L72

Another fix is to abandon `sneakfetch` and rewrite a webhook library from scratch

**Comment by 0x506978656c** [comment]
Struggling to replicate this even with a server's exact files that had this error. Could possibly be a need to change out `sneakfetch` with `node-fetch` however this is untested and only a theory
